apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress-sysyem
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.0.9"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      interval: 1m  
